<?php

return [
    'en'=>[
        "music Fan",
        "Movies Persom",
        "Gamer",
        "Sportsman",
        "Nature Lover",
        "Cooking Enthusiast",
        "Dog Person",
        "Art Enthusiast",
        "Threatre Lover",
        "Exhibition ",
        "Fitness Freak",
        "Hiphop Fan",
        "Photographer",
        "Rapper",
        "Poetic",
        "Talkitive",
        "Dandy ",
        "Traveller",
        "MUA",
        "Cat person",
        "Philosophical ",
        "Amateur Painter",
        "Film Critic ",
        "Dancer",
        "Hip-hoper ",
        "Arcade Gamer",
        "Art Student",
        "Backpacker",
        "Organized Person",
        "vlogger ",
        "Versatile ",
        "Foodie ",
        "Historian ",
        "Belieber",
        "BTS Army",
        "Blink",
        "Swiftie",
        "Unique",
        "Pianist",
        "Guitarist",
        "Band Player",
        "Headphones fanatic",
        "Music fanatic",
        "Won Dancing Award",
        "Won Singing competition Award",
        "Part of a Drama",
        "Formed a band",
        "Lost more than 10kg",
        "Entrepreneurship",
        "Travelled Alone",
        "Run a Marathon",
        "Perfomed as a DJ",
        "Have seen aurora",
        "Released Music Album",
        "Published articles",
        "Encountered a supernatural event",
        "Done Volunteer Work",
        "Travelled to five continents",
        "Cycling for thousands of kilometers",
        "Ordinary but Unique",
        "Interesting soul",
        "One of the billions of stars",
        "Quick replier ",
        "Chatty",
        "Moody",
        "Bookworm",
        "Cutie Pie",
        "Hairstyle Conscious",
        "Insomniac",
        "Fantasy Prone",
        "Innocent",
        "Fashionista",
        "Challenger",
    ],
    'id'=>[
        "musik",
        "Film dan televisi",
        "permainan",
        "gerakan",
        "Suka berjalan di tengah hujan ringan",
        "Suka memasak",
        "Satu orang, satu anjing, satu dunia",
        "Seperti lukisan",
        "Pecinta drama musikal",
        "Pecinta pameran",
        "Suka kebugaran",
        "Hiphop",
        "Juru potret",
        "Seperti rap",
        "Suka menulis puisi",
        "Dari obrolan dangkal di depan Anda hingga puisi dan jarak",
        "Cintai kehidupan borjuis kecil",
        "Setidaknya satu perjalanan",
        "Ahli perawatan kulit",
        "Kucing awan",
        "Dari Puisi dan Lagu hingga Filsafat Kehidupan",
        "Amatir lukisan cat minyak",
        "Suka menulis review film",
        "Menari adalah hidup",
        "Hip-hop adalah sikap",
        "Sangat pandai menangkap boneka",
        "Mahasiswa seni",
        "Backpacker",
        "Lipstik yang kuat untuk teh kantor dapat ditempatkan secara berurutan",
        "vlog",
        "Pertemuan sampel piano, catur, kaligrafi dan lukisan",
        "Panduan makanan jalan kaki",
        "Kenal China selama lima ribu tahun",
        "Mayday menemani masa mudaku",
        "Seperti Jay selama lebih dari sepuluh tahun",
        "Penggemar setia celana baru",
        "Daai Qingfeng",
        "Bintang paling terang di langit malam dengan keindahan yang tak tertandingi",
        "Bisa bermain piano",
        "Sepuluh gitar level satu untuk pergi ke dunia",
        "Berpartisipasilah dalam pertunjukan band sebagai seorang amatir",
        "Tidak bisa hidup tanpa headphone",
        "Tidak bisa hidup tanpa musik",
        "Kompetisi tari pemenang penghargaan",
        "Kompetisi menyanyi dimenangkan",
        "Jadilah ekstra",
        "Membentuk sebuah band",
        "Kehilangan lebih dari 20 kati",
        "Memulai bisnis",
        "Bepergian secara mandiri",
        "Setengah maraton",
        "Diatur untuk sebuah bintang",
        "Telah melihat aurora",
        "Merilis album",
        "Artikel yang diterbitkan",
        "Menemukan peristiwa supernatural",
        "Didukung",
        "Bepergian ke lima benua",
        "Bersepeda sejauh ribuan kilometer",
        "Orang biasa yang unik",
        "Jiwa yang menarik",
        "Salah satu dari milyaran bintang",
        "Bacalah kembali",
        "Obrolan",
        "Dingin tinggi intermiten",
        "Wajah Xueba",
        "Stroberi sangat lucu",
        "Potong rambut Anda sebelum pergi",
        "Insomnia berulang",
        "Pasien dengan penyakit sekunder",
        "Tie Hanhan",
        "Semuanya bisa modis",
        "Raja terkuat"
    ]
];
