<?php
return [
    '1'=>'fun',
    '40'=>'exercise',
    '41'=>'travel',
    '42'=>'fashion',
    '43'=>'pets',
    '44'=>'gourmet',
    '45'=>'cartoon',
    '46'=>'reading',
    '47'=>'movies',
    '48'=>'music',
    '49'=>'make_friends',
    '50'=>'video_games',
    '51'=>'pretty',
    '52'=>'passionate',
    '53'=>'introvert',
    '54'=>'learn_languages',
    '55'=>'news',
    '56'=>'dating'
];
